CREATE TABLE Z_DOC_CTRL_LOG (
Z_LOG_ID IDENTITY,
BIRUNID BIGINT,
TRMNL NUMERIC(3,0),
GS_USER CHAR(10),
DOC_KEY CHAR(125),
DOC_TYPE CHAR(250),
ACTION CHAR(30),
DATE_ACCESSED DATETIME,
PRIMARY KEY(Z_LOG_ID)
);